services:
    sheer.admsql.listener:
        class: sheer\admsql\event\listener
        arguments:
            - %core.root_path%
            - @template
        tags:
            - { name: event.listener }
